baseURL = "https://dspille.github.io/SecureOps_Insights/"
languageCode = "en-us"
title = "SecureOps Insights"
theme = "PaperMod"

[params]
[params.profileMode]
enabled = true
title = "Welcome to My Blog"
subtitle = "Sharing thoughts on Fortinet, technology, and life"
[[params.profileMode.buttons]]
name = "About"
url = "about"
[[params.profileMode.buttons]]
name = "Tutorials"
url = "tutorials"
[[params.profileMode.buttons]]
name = "Best Practices"
url = "best-practices"

[[params.socialIcons]]
name = "github"
url = "https://github.com/ftnt-dspille"
[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/dylan-spille/"

ShowReadingTime = true
ShowCodeCopyButtons = true
ShowToc = true
TocOpen = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowWordCount = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "tutorials"
name = "Tutorials"
url = "/tutorials/"
weight = 10

[[menu.main]]
identifier = "best-practices"
name = "Best Practices"
url = "/best-practices/"
weight = 40

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 50